const CORE_TEXTS = {
    SERVER_ERRORS: {
        //400
        E400: { es: 'Petición incorrecta', en: 'Bad request' },
        //401
        E401: { es: 'No autorizado', en: 'Unauthorized' },
        E401_1: { es: 'Credenciales inválidas', en: 'Invalid credentials' },
        //403
        E403: { es: 'Prohibido', en: 'Forbidden' },
        E403_1: { es: 'No tiene permiso para acceder a este recurso', en: 'You do not have permission to access this resource' },
        E403_2: { es: 'Cuenta no verificada', en: 'Account not verified' },
        //404
        E404: { es: 'No encontrado.', en: 'Not found.' },
        E404_1: { es: 'Usuario no encontrado.', en: 'User not found.' },
        E404_2: { es: 'Curso no encontrado.', en: 'Course not found.' },
        E404_3: { es: 'Estudiante no encontrado.', en: 'Student not found.' },
        //409
        E409: { es: 'Conflicto', en: 'Conflict' },
        E409_1: { es: 'Email no disponible', en: 'Email not available' },
        //422
        E422: { es: 'Entidad no procesable', en: 'Unprocessable entity' },
        //500
        E500: { es: 'Error interno del servidor.', en: 'Internal server error.' },
        E500_1: { es: 'Error enviando el correo electrónico.', en: 'Error sending email.' },
    },
    VALIDATIONS_REQUIRED: { es: 'Campo obligatorio', en: 'Required field' },
    VALIDATIONS_EMAIL: { es: 'Correo electrónico inválido.', en: 'Invalid email.' },
    VALIDATIONS_MIN: { es: 'Debe tener al menos {{min}} caracteres', en: 'Must have at least {{min}} characters' },
    VALIDATIONS_MAX: { es: 'Debe tener como máximo {{max}} caracteres', en: 'Must have at most {{max}} characters' },
    VALIDATIONS_PASSWORD_MINUPPERCASE: { es: 'Debe tener como mínimo {{min}} mayúscula{{#plural}}s{{/plural}}', en: 'Must have at least {{min}} uppercase character{{#plural}}s{{/plural}}' },
    VALIDATIONS_PASSWORD_MINLOWERCASE: { es: 'Debe tener como mínimo {{min}} minúscula{{#plural}}s{{/plural}}', en: 'Must have at least {{min}} lowercase character{{#plural}}s{{/plural}}' },
    VALIDATIONS_PASSWORD_MINNUMBERS: { es: 'Debe tener como mínimo {{min}} número{{#plural}}s{{/plural}}', en: 'Must have at least {{min}} number{{#plural}}s{{/plural}}' },
    VALIDATIONS_PASSWORD_MINSYMBOLS: { es: 'Debe tener como mínimo {{min}} símbolo{{#plural}}s{{/plural}}', en: 'Must have at least {{min}} symbol{{#plural}}s{{/plural}}' },
    VALIDATIONS_EQUAL_TO: { es: 'Los datos ingresados no coinciden', en: 'The entered data does not match' },
    VALIDATIONS_DATE: { es: 'Fecha inválida', en: 'Invalid date' },
    VALIDATIONS_URL: { es: 'Url inválida', en: 'Invalid url' },
    VALIDATIONS_NUMBER: { es: 'Número inválido', en: 'Invalid number' },
    VALIDATIONS_MIN_NUMBER: { es: 'El valor mínimo es {{min}}', en: 'The minimum value is {{min}}' },
    VALIDATIONS_MAX_NUMBER: { es: 'El valor máximo es {{max}}', en: 'The maximum value is {{max}}' },
    VALIDATIONS_MORE_THAN_NUMBER: { es: 'El valor debe ser mayor que {{moreThan}}', en: 'The value must be greater than {{moreThan}}' },
    VALIDATIONS_LESS_THAN_NUMBER: { es: 'El valor debe ser menor que {{lessThan}}', en: 'The value must be less than {{lessThan}}' },
    VALIDATIONS_INTEGER: { es: 'El valor debe ser un número entero', en: 'The value must be an integer' },
    VALIDATIONS_MIN_DATE: { es: 'La fecha mínima es {{min}}', en: 'The minimum date is {{min}}' },
    VALIDATIONS_MAX_DATE: { es: 'La fecha máxima es {{max}}', en: 'The maximum date is {{max}}' },
    GENERIC_ERROR: { es: 'Ha ocurrido un error', en: 'An error has occurred' },
    GENERIC_SUCCESS: { es: 'Operación exitosa', en: 'Successful operation' },
    GENERIC_CREATE: { es: 'Crear', en: 'Create' },
    GENERIC_DELETE_ALL: { es: 'Eliminar todo', en: 'Delete all' },
    GENERIC_CLOSE: { es: 'Cerrar', en: 'Close' },
    GENERIC_CONFIRM: { es: 'Confirmar', en: 'Confirm' },
    GENERIC_EDIT: { es: 'Editar', en: 'Edit' },
    GENERIC_VIEW_DETAILS: { es: 'Ver detalles', en: 'View details' },
    GENERIC_DELETE: { es: 'Eliminar', en: 'Delete' },
    GENERIC_MORE_INFO: { es: 'Mas información', en: 'More info' },
    GENERIC_DELETE_DESCRIPTION_CONFIRM: { es: '¿Estas seguro de que deseas eliminar esto?', en: 'Are you sure you want to delete this?' },
    GENERIC_DELETE_ALL_DESCRIPTION_CONFIRM: { es: '¿Estas seguro de que deseas eliminar todo?', en: 'Are you sure you want to delete all?' },
    GENERIC_SUBMIT: { es: 'Enviar', en: 'Submit' },
    COOMING_SOON: { es: 'Próximamente...', en: 'Cooming soon...' },
    GENERIC_ACTIONS: { es: 'Acciones', en: 'Actions' },
    GENERIC_BACK: { es: 'Atrás', en: 'Back' },
    GENERIC_CANCEL: { es: 'Cancelar', en: 'Cancel' },
    GENERIC_NEXT: { es: 'Siguiente', en: 'Next' },
    GENERIC_FINISH: { es: 'Finalizar', en: 'Finish' },
    GENERIC_ADD: { es: 'Agregar', en: 'Add' },
    GENERIC_EDIT_SELECTION: { es: 'Editar selección', en: 'Edit selection' },
    GENERIC_DELETE_SELECTION: { es: 'Eliminar selección', en: 'Delete selection' },
    VALIDATIONS_ONE_OF: { es: 'Debe ser uno de los siguientes valores: {{oneOf}}', en: 'Must be one of the following values: {{oneOf}}' },
    GENERIC_ZOOM_OUT: { es: 'Alejar', en: 'Zoom out' },
    GENERIC_ZOOM_IN: { es: 'Acercar', en: 'Zoom in' },
    GENERIC_AVATAR_EDITOR_TITLE: { es: 'Foto de perfil', en: 'Profile picture' },
    VALIDATIONS_NAME: { es: 'Solo se permiten letras y espacios', en: 'Only letters and spaces are allowed' },
    GENERIC_DATE: { es: 'Fecha', en: 'Date' },
    GENERIC_LABEL_LABEL: { es: 'Etiqueta', en: 'Label' },
    GENERIC_LABEL_PLACEHOLDER: { es: 'Ingrese una etiqueta', en: 'Enter a label' },
    GENERIC_PLACEHOLDER_LABEL: { es: 'Placeholder', en: 'Placeholder' },
    GENERIC_PLACEHOLDER_PLACEHOLDER: { es: 'Ingrese un placeholder', en: 'Enter a placeholder' },
    GENERIC_DEFAULT_VALUE: { es: 'Valor por defecto', en: 'Default value' },
    GENERIC_DEFAULT_VALUE_PLACEHOLDER: { es: 'Ingrese un valor por defecto', en: 'Enter a default value' },
    GENERIC_POINTS_TO_ADD_LABEL: { es: 'Puntos a agregar', en: 'Points to add' },
    GENERIC_POINTS_TO_ADD_PLACEHOLDER: { es: 'Ingrese la cantidad de puntos a agregar', en: 'Enter the amount of points to add' },
    GENERIC_MIN_LABEL: { es: 'Mínimo', en: 'Minimum' },
    GENERIC_MAX_LABEL: { es: 'Máximo', en: 'Maximum' },
    DOWNLOAD_XLSX: { es: 'Descargar excel', en: 'Download excel' },
    FILES_INPUT_MAX_FILES_REACHED: { es: 'Archivos restantes: {{maxFiles}}', en: 'Remaining files: {{maxFiles}}' },
};


export default CORE_TEXTS;
