const CORE_TEXTS = {
    SERVER_ERRORS: {
        //Generic errors
        E500: { es: 'Error interno del servidor.', en: 'Internal server error.' },
        E400: { es: 'Petición incorrecta', en: 'Bad request' },
        E401: { es: 'No autorizado', en: 'Unauthorized' },
        E403: { es: 'Prohibido', en: 'Forbidden' },
        E404: { es: 'No encontrado.', en: 'Not found.' },
        E409: { es: 'Conflicto', en: 'Conflict' },
        E422: { es: 'Entidad no procesable', en: 'Unprocessable entity' },
        //Custom errors
        E401_1: { es: 'Credenciales inválidas', en: 'Invalid credentials' },
        E409_1: { es: 'Email no disponible', en: 'Email not available' },
    },
    VALIDATIONS_REQUIRED: { es: 'Campo obligatorio', en: 'Required field' },
    VALIDATIONS_EMAIL: { es: 'Correo electrónico inválido.', en: 'Invalid email.' },
    VALIDATIONS_MIN: { es: 'Debe tener al menos {{min}} caracteres', en: 'Must have at least {{min}} characters' },
    VALIDATIONS_MAX: { es: 'Debe tener como máximo {{max}} caracteres', en: 'Must have at most {{max}} characters' },
    VALIDATIONS_PASSWORD_MINUPPERCASE: { es: 'Debe tener como mínimo {{min}} mayúscula{{#plural}}s{{/plural}}', en: 'Must have at least {{min}} uppercase character{{#plural}}s{{/plural}}' },
    VALIDATIONS_PASSWORD_MINLOWERCASE: { es: 'Debe tener como mínimo {{min}} minúscula{{#plural}}s{{/plural}}', en: 'Must have at least {{min}} lowercase character{{#plural}}s{{/plural}}' },
    VALIDATIONS_PASSWORD_MINNUMBERS: { es: 'Debe tener como mínimo {{min}} número{{#plural}}s{{/plural}}', en: 'Must have at least {{min}} number{{#plural}}s{{/plural}}' },
    VALIDATIONS_PASSWORD_MINSYMBOLS: { es: 'Debe tener como mínimo {{min}} símbolo{{#plural}}s{{/plural}}', en: 'Must have at least {{min}} symbol{{#plural}}s{{/plural}}' },
    VALIDATIONS_EQUAL_TO: { es: 'Los datos ingresados no coinciden', en: 'The entered data does not match' },
    VALIDATIONS_DATE: { es: 'Fecha inválida', en: 'Invalid date' },
    VALIDATIONS_URL: { es: 'Url inválida', en: 'Invalid url' },
    VALIDATIONS_NUMBER: { es: 'Número inválido', en: 'Invalid number' },
    VALIDATIONS_MIN_NUMBER: { es: 'El valor mínimo es {{min}}', en: 'The minimum value is {{min}}' },
    VALIDATIONS_MAX_NUMBER: { es: 'El valor máximo es {{max}}', en: 'The maximum value is {{max}}' },
    VALIDATIONS_MORE_THAN_NUMBER: { es: 'El valor debe ser mayor que {{moreThan}}', en: 'The value must be greater than {{moreThan}}' },
    VALIDATIONS_LESS_THAN_NUMBER: { es: 'El valor debe ser menor que {{lessThan}}', en: 'The value must be less than {{lessThan}}' },
    VALIDATIONS_INTEGER: { es: 'El valor debe ser un número entero', en: 'The value must be an integer' },
    GENERIC_ERROR: { es: 'Ha ocurrido un error', en: 'An error has occurred' },
    GENERIC_SUCCESS: { es: 'Operación exitosa', en: 'Successful operation' },
    GENERIC_ADD: { es: 'Crear', en: 'Create' },
    GENERIC_DELETE_ALL: { es: 'Eliminar todo', en: 'Delete all' },
    GENERIC_CLOSE: { es: 'Cerrar', en: 'Close' },
    GENERIC_CONFIRM: { es: 'Confirmar', en: 'Confirm' },
    GENERIC_EDIT: { es: 'Editar', en: 'Edit' },
    GENERIC_DELETE: { es: 'Eliminar', en: 'Delete' },
    GENERIC_MORE_INFO: { es: 'Mas información', en: 'More info' },
    GENERIC_DELETE_DESCRIPTION_CONFIRM: { es: '¿Estas seguro de que deseas eliminar esto?', en: 'Are you sure you want to delete this?' },
    GENERIC_DELETE_ALL_DESCRIPTION_CONFIRM: { es: '¿Estas seguro de que deseas eliminar todo?', en: 'Are you sure you want to delete all?' },
    GENERIC_SUBMIT: { es: 'Enviar', en: 'Submit' },
    COOMING_SOON: { es: 'Próximamente...', en: 'Cooming soon...' },
    GENERIC_ACTIONS: { es: 'Acciones', en: 'Actions' }
};

export default CORE_TEXTS;
