const TEXTS = {
    EMAIL_LABEL: { es: 'Correo electrónico', en: 'Email' },
    EMAIL_PLACEHOLDER: { es: 'Ingresa tu correo electrónico', en: 'Enter your email' },
    PASSWORD_LABEL: { es: 'Contraseña', en: 'Password' },
    PASSWORD_PLACEHOLDER: { es: 'Ingresa tu contraseña', en: 'Enter your password' },
    LOGIN_BUTTON: { es: 'Iniciar sesión', en: 'Login' },
    LOGIN_PAGE_TITLE: { es: 'Iniciar sesión', en: 'Login' },
    HOME_HEAD_TITLE: { es: 'Edu Organizer', en: 'Edu Organizer' },
    ORGANIZATION_NAME_LABEL: { es: 'Nombre de la organización', en: 'Organization name' },
    ORGANIZATION_NAME_PLACEHOLDER: { es: 'Ingresa el nombre de tu organización', en: 'Enter your organization name' },
    FIRST_NAME_LABEL: { es: 'Nombre', en: 'First name' },
    FIRST_NAME_PLACEHOLDER: { es: 'Ingresa tu nombre', en: 'Enter your first name' },
    LAST_NAME_LABEL: { es: 'Apellido', en: 'Last name' },
    LAST_NAME_PLACEHOLDER: { es: 'Ingresa tu apellido', en: 'Enter your last name' },
    REPEAT_PASSWORD_LABEL: { es: 'Repite tu contraseña', en: 'Repeat your password' },
    REPEAT_PASSWORD_PLACEHOLDER: { es: 'Ingresa tu contraseña nuevamente', en: 'Enter your password again' },
    REGISTER_HEAD_TITLE: { es: 'Registrarse', en: 'Register' },
    REGISTER_HEAD_DESCRIPTION: { es: 'Registra tu organización y empieza a organizar tus clases', en: 'Register your organization and start organizing your classes' },
    REGISTER_PAGE_TITLE: { es: 'Registrarse', en: 'Register' },
    LOGIN_PAGE_RECOVER_PASSWORD_LINK: { es: '¿Olvidaste tu contraseña?', en: 'Forgot your password?' },
    LOGIN_PAGE_REGISTER_LINK: { es: '¿No tienes una cuenta? Regístrate', en: 'Don\'t have an account? Register' },
    REGISTER_PAGE_LOGIN_LINK: { es: '¿Ya tienes una cuenta? Inicia sesión', en: 'Already have an account? Login' },
    MY_ACCOUNT_PAGE_TITLE: { es: 'Mi cuenta', en: 'My account' },
    LOGOUT_BUTTON: { es: 'Cerrar sesión', en: 'Logout' },
    ACCOUNT_BUTTON_TOOLTIP: { es: 'Mi cuenta', en: 'My account' },
    ADMIN_MENU_BUTTON_COURSES: { es: 'Cursos', en: 'Courses' },
    ADMIN_MENU_BUTTON_STUDENTS: { es: 'Estudiantes', en: 'Students' },
    ADMIN_MENU_BUTTON_TEACHERS: { es: 'Profesores', en: 'Teachers' },
    ADMIN_MENU_BUTTON_CLASS_SESSIONS: { es: 'Clases', en: 'Class sessions' },
    COURSE_NAME_LABEL: { es: 'Nombre del curso', en: 'Course name' },
    COURSE_NAME_PLACEHOLDER: { es: 'Ingresa el nombre del curso', en: 'Enter the course name' },
    CREATE_COURSE_MODAL_TITLE: { es: 'Crear curso', en: 'Create course' },
    GO_COURSE: { es: 'Ver detalles del curso', en: 'Go course details' },
    GO_EDIT_COURSE: { es: 'Editar curso', en: 'Go edit course' },
    DELETE_COURSE_TOOLTIP: { es: 'Eliminar curso', en: 'Delete course' },
    GO_BACK_COURSES: { es: 'Volver a cursos', en: 'Go back courses' },
    COURSE_PAGE_SUBTITLE: { es: 'Aqui puedes ver y editar la información del curso', en: 'Here you can see and edit the course information' },
    TEACHERS_PAGE_TITLE: { es: 'Profesores', en: 'Teachers' },
    COURSE_PAGE_TITLE: { es: 'Detalles del curso', en: 'Course details' },
    COURSE_ID_LABEL: { es: 'ID del curso', en: 'Course ID' },
    COURSE_SHORT_ID_LABEL: { es: 'Identificador del curso', en: 'Course short ID' },
    STUDENT_FIRST_NAME_LABEL: { es: 'Nombre', en: 'First name' },
    STUDENT_LAST_NAME_LABEL: { es: 'Apellido', en: 'Last name' },
    GO_STUDENT: { es: 'Ver estudiante', en: 'Go student' },
    CREATE_COURSE_PAGE_TITLE: { es: 'Crear curso', en: 'Create course' },
    CREATE_COURSE_PAGE_SUBTITLE: { es: 'Aqui puedes crear un nuevo curso', en: 'Here you can create a new course' },
    CREATE_STUDENT_PAGE_TITLE: { es: 'Crear estudiante', en: 'Create student' },
    CREATE_STUDENT_PAGE_SUBTITLE: { es: 'Aqui puedes crear un nuevo estudiante', en: 'Here you can create a new student' },
    GO_BACK_STUDENTS: { es: 'Volver a estudiantes', en: 'Go back students' },
    STUDENT_ID_LABEL: { es: 'ID del estudiante', en: 'Student ID' },
    STUDENT_PAGE_TITLE: { es: 'Detalles del estudiante', en: 'Student details' },
    STUDENT_PAGE_SUBTITLE: { es: 'Aqui puedes ver y editar la información del estudiante', en: 'Here you can see and edit the student information' },
    STUDENT_FIRST_NAME_PLACEHOLDER: { es: 'Ingresa el nombre del estudiante', en: 'Enter the student first name' },
    STUDENT_LAST_NAME_PLACEHOLDER: { es: 'Ingresa el apellido del estudiante', en: 'Enter the student last name' },
    CLASS_SESSIONS_PAGE_TITLE: { es: 'Clases', en: 'Class sessions' },
    CLASS_SESSIONS_PAGE_SUBTITLE: { es: 'Aqui puedes ver los registros de asistencia', en: 'Here you can see the attendance records' },
    COURSES_PAGE_TITLE: { es: 'Cursos', en: 'Courses' },
    COURSES_PAGE_SUBTITLE: { es: 'Aqui puedes ver todos los cursos', en: 'Here you can see all the courses' },
    STUDENTS_PAGE_TITLE: { es: 'Estudiantes', en: 'Students' },
    STUDENTS_PAGE_SUBTITLE: { es: 'Aqui puedes ver todos los estudiantes', en: 'Here you can see all the students' },
    TEACHERS_PAGE_SUBTITLE: { es: 'Aqui puedes ver todos los profesores', en: 'Here you can see all the teachers' },
    STUDENT_COURSE_LABEL: { es: 'Curso', en: 'Course' },
    AVAIBLE_STUDENTS_LIST_CARD_TITLE: { es: 'Estudiantes disponibles', en: 'Avaible students' },
    COURSE_STUDENTS_LIST_CARD_TITLE: { es: 'Estudiantes del curso', en: 'Course students' },
    COURSE_CREATE_STUDENT_CARD_TITLE: { es: 'Nuevo estudiante', en: 'New student' },
    COURSE_CREATE_STUDENT_CARD_HELP: { es: 'Los estudiantes que agregues por este medio se crearán al completar la creación del curso y seran asignados a este', en: 'The students you add this way will be created when you complete the course creation and will be assigned to it' },
    AVAIBLE_STUDENTS_LIST_CARD_HELP: { es: 'Estos son los estudiantes que actualmente no estan asignados a ningun curso y estan disponibles para ser agregados. Haz clic en uno para agregarlo al curso', en: 'These are the students who are currently not assigned to any course and are available to be added. Click on one to add it to the course' },
    COURSE_STUDENTS_LIST_CARD_HELP: { es: 'Estos son los estudiantes que seran asignados al curso. Si deseas quitar un estudiante puedes hacerlo haciendo clic sobre el', en: 'These are the students who will be assigned to the course. If you want to remove a student you can do it by clicking on it' },
    DELETE_COURSE_MODAL_TITLE: { es: 'Eliminar curso', en: 'Delete course' },
    DELETE_COURSE_MODAL_CONTENT: { es: '¿Estás seguro que deseas eliminar este curso?', en: 'Are you sure you want to delete this course?' },
    COURSE_ACCESS_PIN_LABEL: { es: 'PIN de acceso', en: 'Access PIN' },
    COURSE_ACCESS_PIN_PLACEHOLDER: { es: 'Ingresa el PIN de acceso', en: 'Enter the access PIN' },
    SET_COURSE_DATA_TITLE: { es: 'Datos del curso', en: 'Course data' },
    SET_COURSE_STUDENTS_TITLE: { es: 'Seleccion de estudiantes', en: 'Students selection' },
    SET_COURSE_CLASS_SESSIONS_CONFIG_TITLE: { es: 'Configuracion de clases', en: 'Class sessions config' },
}

export default TEXTS